// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.176.0
//   protoc               v3.12.4
// source: responses/create-coworking.proto

/* eslint-disable */
import * as _m0 from "protobufjs/minimal";

export const protobufPackage = "create_workspace_response";

export interface CreateCoworkingResponse {
  UUID: string;
}

function createBaseCreateCoworkingResponse(): CreateCoworkingResponse {
  return { UUID: "" };
}

export const CreateCoworkingResponse = {
  encode(message: CreateCoworkingResponse, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.UUID !== "") {
      writer.uint32(10).string(message.UUID);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): CreateCoworkingResponse {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreateCoworkingResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.UUID = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CreateCoworkingResponse {
    return { UUID: isSet(object.UUID) ? globalThis.String(object.UUID) : "" };
  },

  toJSON(message: CreateCoworkingResponse): unknown {
    const obj: any = {};
    if (message.UUID !== "") {
      obj.UUID = message.UUID;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CreateCoworkingResponse>, I>>(base?: I): CreateCoworkingResponse {
    return CreateCoworkingResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CreateCoworkingResponse>, I>>(object: I): CreateCoworkingResponse {
    const message = createBaseCreateCoworkingResponse();
    message.UUID = object.UUID ?? "";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
