// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v3.12.4
// source: contracts/requests/add-image-to-coworking.proto

package requests

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddImageToCoworkingRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CoworkingUuid string `protobuf:"bytes,1,opt,name=coworking_uuid,json=coworkingUuid,proto3" json:"coworking_uuid,omitempty"`
	ImageData     []byte `protobuf:"bytes,2,opt,name=image_data,json=imageData,proto3" json:"image_data,omitempty"`
	ImageFilename string `protobuf:"bytes,3,opt,name=image_filename,json=imageFilename,proto3" json:"image_filename,omitempty"`
}

func (x *AddImageToCoworkingRequest) Reset() {
	*x = AddImageToCoworkingRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_contracts_requests_add_image_to_coworking_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddImageToCoworkingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddImageToCoworkingRequest) ProtoMessage() {}

func (x *AddImageToCoworkingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_requests_add_image_to_coworking_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddImageToCoworkingRequest.ProtoReflect.Descriptor instead.
func (*AddImageToCoworkingRequest) Descriptor() ([]byte, []int) {
	return file_contracts_requests_add_image_to_coworking_proto_rawDescGZIP(), []int{0}
}

func (x *AddImageToCoworkingRequest) GetCoworkingUuid() string {
	if x != nil {
		return x.CoworkingUuid
	}
	return ""
}

func (x *AddImageToCoworkingRequest) GetImageData() []byte {
	if x != nil {
		return x.ImageData
	}
	return nil
}

func (x *AddImageToCoworkingRequest) GetImageFilename() string {
	if x != nil {
		return x.ImageFilename
	}
	return ""
}

var File_contracts_requests_add_image_to_coworking_proto protoreflect.FileDescriptor

var file_contracts_requests_add_image_to_coworking_proto_rawDesc = []byte{
	0x0a, 0x2f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x73, 0x2f, 0x72, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x73, 0x2f, 0x61, 0x64, 0x64, 0x2d, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x2d, 0x74,
	0x6f, 0x2d, 0x63, 0x6f, 0x77, 0x6f, 0x72, 0x6b, 0x69, 0x6e, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x16, 0x61, 0x64, 0x64, 0x5f, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x5f, 0x74, 0x6f, 0x5f,
	0x63, 0x6f, 0x77, 0x6f, 0x72, 0x6b, 0x69, 0x6e, 0x67, 0x22, 0x89, 0x01, 0x0a, 0x1a, 0x41, 0x64,
	0x64, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x54, 0x6f, 0x43, 0x6f, 0x77, 0x6f, 0x72, 0x6b, 0x69, 0x6e,
	0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x25, 0x0a, 0x0e, 0x63, 0x6f, 0x77, 0x6f,
	0x72, 0x6b, 0x69, 0x6e, 0x67, 0x5f, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0d, 0x63, 0x6f, 0x77, 0x6f, 0x72, 0x6b, 0x69, 0x6e, 0x67, 0x55, 0x75, 0x69, 0x64, 0x12,
	0x1d, 0x0a, 0x0a, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x09, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x44, 0x61, 0x74, 0x61, 0x12, 0x25,
	0x0a, 0x0e, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x5f, 0x66, 0x69, 0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x46, 0x69, 0x6c,
	0x65, 0x6e, 0x61, 0x6d, 0x65, 0x42, 0x32, 0x5a, 0x30, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x6a, 0x64, 0x65, 0x73, 0x30, 0x31, 0x2f, 0x63, 0x6f, 0x77, 0x72, 0x65,
	0x6e, 0x74, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x73,
	0x2f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_contracts_requests_add_image_to_coworking_proto_rawDescOnce sync.Once
	file_contracts_requests_add_image_to_coworking_proto_rawDescData = file_contracts_requests_add_image_to_coworking_proto_rawDesc
)

func file_contracts_requests_add_image_to_coworking_proto_rawDescGZIP() []byte {
	file_contracts_requests_add_image_to_coworking_proto_rawDescOnce.Do(func() {
		file_contracts_requests_add_image_to_coworking_proto_rawDescData = protoimpl.X.CompressGZIP(file_contracts_requests_add_image_to_coworking_proto_rawDescData)
	})
	return file_contracts_requests_add_image_to_coworking_proto_rawDescData
}

var file_contracts_requests_add_image_to_coworking_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_contracts_requests_add_image_to_coworking_proto_goTypes = []interface{}{
	(*AddImageToCoworkingRequest)(nil), // 0: add_image_to_coworking.AddImageToCoworkingRequest
}
var file_contracts_requests_add_image_to_coworking_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_contracts_requests_add_image_to_coworking_proto_init() }
func file_contracts_requests_add_image_to_coworking_proto_init() {
	if File_contracts_requests_add_image_to_coworking_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_contracts_requests_add_image_to_coworking_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddImageToCoworkingRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_contracts_requests_add_image_to_coworking_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_contracts_requests_add_image_to_coworking_proto_goTypes,
		DependencyIndexes: file_contracts_requests_add_image_to_coworking_proto_depIdxs,
		MessageInfos:      file_contracts_requests_add_image_to_coworking_proto_msgTypes,
	}.Build()
	File_contracts_requests_add_image_to_coworking_proto = out.File
	file_contracts_requests_add_image_to_coworking_proto_rawDesc = nil
	file_contracts_requests_add_image_to_coworking_proto_goTypes = nil
	file_contracts_requests_add_image_to_coworking_proto_depIdxs = nil
}
